"""store leads json in search history

Revision ID: 1890aad2a283
Revises: ba9a0bee3a58
Create Date: 2026-07-10 01:01:21.330642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1890aad2a283'
down_revision: Union[str, Sequence[str], None] = 'ba9a0bee3a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'search_history',
        sa.Column('leads', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'leads')
    # ### end Alembic commands ###
