"""rolling quota window and search history

Revision ID: ba9a0bee3a58
Revises: 20b28be3480c
Create Date: 2026-07-09 20:01:24.392261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9a0bee3a58'
down_revision: Union[str, Sequence[str], None] = '20b28be3480c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.add_column('search_usage', sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_usage_subject_day'), 'search_usage', type_='unique')
    op.drop_index(op.f('ix_search_usage_subject'), table_name='search_usage')
    op.create_index(op.f('ix_search_usage_subject'), 'search_usage', ['subject'], unique=True)
    op.drop_column('search_usage', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_usage', sa.Column('day', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_search_usage_subject'), table_name='search_usage')
    op.create_index(op.f('ix_search_usage_subject'), 'search_usage', ['subject'], unique=False)
    op.create_unique_constraint(op.f('uq_usage_subject_day'), 'search_usage', ['subject', 'day'], postgresql_nulls_not_distinct=False)
    op.drop_column('search_usage', 'last_used_at')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_table('search_history')
    # ### end Alembic commands ###
