"""add email to cached_leads

Revision ID: f075339bb8bb
Revises: 67d863c6f0f3
Create Date: 2026-07-05 21:12:02.811275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f075339bb8bb'
down_revision: Union[str, Sequence[str], None] = '67d863c6f0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_leads', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_leads', 'email')
    # ### end Alembic commands ###
